<?php

return [
    [
        'title' => 'Laravel Developer',
        'tags' => 'laravel, php, backend',
        'company' => 'Acme Corp',
        'location' => 'New York, NY',
        'email' => 'hr@acme.com',
        'website' => 'https://www.acme.com',
        'description' => 'We are looking for a Laravel developer experienced with Laravel, PHP, and MySQL.',
    ],
    [
        'title' => 'React Developer',
        'tags' => 'react, javascript, frontend',
        'company' => 'Pixel Studios',
        'location' => 'San Francisco, CA',
        'email' => 'jobs@pixelstudios.com',
        'website' => 'https://www.pixelstudios.com',
        'description' => 'Frontend position for skilled React developers with knowledge of modern JS frameworks.',
    ],
    [
        'title' => 'Full Stack Engineer',
        'tags' => 'php, react, fullstack',
        'company' => 'TechNova',
        'location' => 'Austin, TX',
        'email' => 'careers@technova.com',
        'website' => 'https://www.technova.com',
        'description' => 'Full stack role for developers comfortable with Laravel and React.',
    ],
    [
        'title' => 'Python Developer',
        'tags' => 'python, flask, backend',
        'company' => 'DataSoft',
        'location' => 'Boston, MA',
        'email' => 'jobs@datasoft.com',
        'website' => 'https://www.datasoft.com',
        'description' => 'Join our backend team to build scalable APIs using Flask.',
    ],
    [
        'title' => 'Java Developer',
        'tags' => 'java, spring, backend',
        'company' => 'BankWare',
        'location' => 'Chicago, IL',
        'email' => 'hr@bankware.com',
        'website' => 'https://www.bankware.com',
        'description' => 'Java backend development role focused on finance software.',
    ],
    [
        'title' => 'UI/UX Designer',
        'tags' => 'ui, ux, design',
        'company' => 'Creative Minds',
        'location' => 'Seattle, WA',
        'email' => 'design@creativeminds.com',
        'website' => 'https://www.creativeminds.com',
        'description' => 'We’re looking for a creative UI/UX designer to work closely with frontend teams.',
    ],
    [
        'title' => 'DevOps Engineer',
        'tags' => 'devops, aws, ci/cd',
        'company' => 'DeployPro',
        'location' => 'Denver, CO',
        'email' => 'devops@deploypro.com',
        'website' => 'https://www.deploypro.com',
        'description' => 'Help us build efficient CI/CD pipelines and manage AWS infrastructure.',
    ],
    [
        'title' => 'Mobile App Developer',
        'tags' => 'flutter, mobile, android',
        'company' => 'Appify',
        'location' => 'Remote',
        'email' => 'careers@appify.com',
        'website' => 'https://www.appify.com',
        'description' => 'Mobile app developer wanted for Flutter-based project.',
    ],
    [
        'title' => 'Product Manager',
        'tags' => 'product, agile, planning',
        'company' => 'InnovaTech',
        'location' => 'Atlanta, GA',
        'email' => 'pm@innovatech.com',
        'website' => 'https://www.innovatech.com',
        'description' => 'Lead product planning and execution from conception to launch.',
    ],
    [
        'title' => 'Technical Support Engineer',
        'tags' => 'support, troubleshooting, tech',
        'company' => 'HelpFast',
        'location' => 'Houston, TX',
        'email' => 'support@helpfast.com',
        'website' => 'https://www.helpfast.com',
        'description' => 'Provide technical support and customer assistance via chat and email.',
    ],
];
